const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store'}});
const text=(s)=>new Response(s,{status:200,headers:{'content-type':'text/plain;charset=UTF-8'}});
const clean=v=>String(v??'').trim();
const b64=a=>btoa(String.fromCharCode(...new Uint8Array(a))).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
async function hmac(secret,data){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(data)))}
async function makeToken(env){const exp=Date.now()+12*60*60*1000,body=b64(new TextEncoder().encode(String(exp)));return body+'.'+await hmac(env.ADMIN_PASSWORD,body)}
async function adminOK(req,env){if(!env.ADMIN_PASSWORD)return false;const a=req.headers.get('authorization')||'';if(!a.startsWith('Bearer '))return false;const [body,sig]=a.slice(7).split('.');if(!body||!sig)return false;try{const raw=body.replaceAll('-','+').replaceAll('_','/')+'==';const exp=Number(new TextDecoder().decode(Uint8Array.from(atob(raw),c=>c.charCodeAt(0))));return exp>Date.now()&&(await hmac(env.ADMIN_PASSWORD,body))===sig}catch{return false}}
const CATALOG={
 missiles:[['موشک عادی','missiles_normal',10000],['موشک پیشرفته','missiles_advanced',25000],['موشک فوق پیشرفته','missiles_super',50000],['موشک سنگین','missiles_heavy',75000],['موشک سنگین پیشرفته','missiles_heavy_advanced',120000],['موشک دوربرد','missiles_long',180000],['موشک دوربرد پیشرفته','missiles_long_advanced',250000],['موشک بسیار دوربرد','missiles_very_long',400000],['موشک بسیار دوربرد پیشرفته','missiles_very_long_advanced',600000],['موشک ویژه','missiles_special',1000000]],
 military:[['سرباز عادی','military_normal',1000],['سرباز پیشرفته','military_advanced',2500],['سرباز ویژه','military_special',5000],['سرباز لجستیکی','military_logistics',7500],['سرباز سنگین','military_heavy',10000],['سرباز سنگین پیشرفته','military_heavy_advanced',15000],['فرمانده','commander',25000],['فرمانده پیشرفته','commander_advanced',50000],['فرمانده ویژه','commander_special',100000],['فرمانده کل','commander_general',250000]],
 defense:[['پدافند عادی','defense_normal',15000],['پدافند پیشرفته','defense_advanced',35000],['پدافند فوق پیشرفته','defense_super',75000],['پدافند کوتاه‌برد','defense_short',100000],['پدافند کوتاه‌برد پیشرفته','defense_short_advanced',175000],['پدافند میان‌برد','defense_medium',250000],['پدافند میان‌برد پیشرفته','defense_medium_advanced',400000],['پدافند دوربرد','defense_long',600000],['پدافند دوربرد پیشرفته','defense_long_advanced',1000000],['پدافند بسیار پیشرفته','defense_very_advanced',2000000]],
 fighters:[['جنگنده عادی','fighter_normal',5000000],['جنگنده پیشرفته','fighter_advanced',10000000],['جنگنده فوق پیشرفته','fighter_super',20000000],['جنگنده سبک','fighter_light',25000000],['جنگنده سبک پیشرفته','fighter_light_advanced',40000000],['جنگنده سنگین','fighter_heavy',60000000],['جنگنده سنگین پیشرفته','fighter_heavy_advanced',90000000],['جنگنده دوربرد','fighter_long',120000000],['جنگنده دوربرد پیشرفته','fighter_long_advanced',175000000],['جنگنده بسیار پیشرفته','fighter_very_advanced',250000000]],
 bombers:[['بمب‌افکن عادی','bomber_normal',30000000],['بمب‌افکن پیشرفته','bomber_advanced',60000000],['بمب‌افکن فوق پیشرفته','bomber_super',120000000],['بمب‌افکن سبک','bomber_light',150000000],['بمب‌افکن سبک پیشرفته','bomber_light_advanced',200000000],['بمب‌افکن سنگین','bomber_heavy',300000000],['بمب‌افکن سنگین پیشرفته','bomber_heavy_advanced',450000000],['بمب‌افکن دوربرد','bomber_long',600000000],['بمب‌افکن دوربرد پیشرفته','bomber_long_advanced',800000000],['بمب‌افکن بسیار پیشرفته','bomber_very_advanced',1000000000]],
 ships:[['ناو عادی','ship_normal',100000000],['ناو پیشرفته','ship_advanced',200000000],['ناو فوق پیشرفته','ship_super',400000000],['ناو سبک','ship_light',500000000],['ناو سبک پیشرفته','ship_light_advanced',750000000],['ناو سنگین','ship_heavy',1000000000],['ناو سنگین پیشرفته','ship_heavy_advanced',1500000000],['ناو دوربرد','ship_long',2000000000],['ناو دوربرد پیشرفته','ship_long_advanced',3000000000],['ناو بسیار پیشرفته','ship_very_advanced',5000000000]]
};
const INCOME=[['مزرعه کوچک','income_small_farm',10000,500],['فروشگاه کوچک','income_small_shop',25000,1200],['کارگاه','income_workshop',50000,2500],['مزرعه بزرگ','income_large_farm',100000,5000],['فروشگاه بزرگ','income_large_shop',200000,10000],['کارخانه کوچک','income_small_factory',500000,25000],['کارخانه بزرگ','income_large_factory',1000000,60000],['شرکت تجاری','income_trade_company',2500000,150000],['شرکت بزرگ','income_large_company',5000000,300000],['مرکز تجاری','income_business_center',10000000,600000],['کارخانه پیشرفته','income_advanced_factory',25000000,1500000],['شرکت بسیار بزرگ','income_very_large_company',50000000,3000000],['مرکز صنعتی','income_industrial_center',100000000,6000000],['مرکز تجاری بزرگ','income_large_business_center',250000000,15000000],['مجموعه اقتصادی بزرگ','income_economic_group',500000000,30000000]];
const META={};for(const [cat,rows] of Object.entries(CATALOG))for(const [name,key,price] of rows)META[key]={name,key,price,category:cat,war:cat!=='defense',defense:cat==='defense'};for(const [name,key,price,daily] of INCOME)META[key]={name,key,price,daily,category:'income'};
const allAssetKeys=Object.values(CATALOG).flat().map(x=>x[1]);
const warKeys=Object.values(CATALOG).filter(k=>k!==CATALOG.defense).flat().map(x=>x[1]);
const defenseKeys=CATALOG.defense.map(x=>x[1]);
const txCode=()=>{const a='ABCDEFGHJKLMNPQRSTUVWXYZ',n='0123456789',pick=s=>Array.from({length:4},()=>s[Math.floor(Math.random()*s.length)]).join('');return pick(a)+'-'+pick(a+n)+'-'+pick(a+n)};
async function setting(env,key,def=null){const r=await env.DB.prepare('SELECT value FROM s8_settings WHERE key=?').bind(key).first();return r?.value??def}
async function tableCols(env,table){const r=await env.DB.prepare(`PRAGMA table_info(${table})`).all();return new Set((r.results||[]).map(x=>x.name))}
async function userSchema(env){const c=await tableCols(env,'users');return {victories:c.has('victories')?'victories':'wins',blocked:c.has('blocked_type')?'blocked_type':'block_type'}}
async function getUser(env,code){return env.DB.prepare('SELECT * FROM users WHERE code=?').bind(code).first()}
async function isBlocked(u){if(!u?.blocked_until)return false;if(u.blocked_until==='permanent')return true;if(u.blocked_until==='season')return true;const t=Date.parse(u.blocked_until);return Number.isFinite(t)&&t>Date.now()}
async function auth(req,env){const code=clean(req.headers.get('x-user-code')).toUpperCase();if(!/^POW\d+$/.test(code))return {error:json({message:'کد کاربری نامعتبر است.'},400)};const u=await getUser(env,code);if(!u)return {error:json({message:'این کد وجود ندارد'},404)};if(await isBlocked(u))return {error:json({message:'حساب کاربری شما مسدود است.'},403)};const p=await env.DB.prepare('SELECT p.*,u.name,u.total_games,u.loyalty_date FROM s8_players p JOIN users u ON u.code=p.user_code WHERE p.user_code=?').bind(code).first();if(!p)return {error:json({message:'در بازی ثبت نام نشده اید'},403)};return {user:u,player:p}}
async function account(env,code){const u=await getUser(env,code);if(!u)return null;const s=await userSchema(env);return {code:u.code,name:u.name,loyalty_date:u.loyalty_date,total_games:Number(u.total_games||0),victories:Number(u[s.victories]||0),blocked:await isBlocked(u)}}
async function ensureSeasonTables(env){/* schema.sql should be applied once; kept as a guard for already-created deployments */}
async function incomeTotal(env,pid){const r=await env.DB.prepare('SELECT kind,qty FROM s8_income_assets WHERE player_id=? AND qty>0').bind(pid).all();return (r.results||[]).reduce((sum,x)=>sum+(META[x.kind]?.daily||0)*Number(x.qty),0)}
async function publicPlayer(env,p){const ar=await env.DB.prepare('SELECT kind,qty FROM s8_income_assets WHERE player_id=? AND qty>0').bind(p.id).all();const assets={};for(const k of allAssetKeys)assets[k]={name:META[k].name,qty:Number(p[k]||0),price:META[k].price};const incomes={};for(const x of ar.results||[])incomes[x.kind]=Number(x.qty);const daily=Object.entries(incomes).reduce((s,[k,q])=>s+(META[k]?.daily||0)*q,0);return {id:p.id,code:p.user_code,name:p.name,country:p.country,dollars:Number(p.dollars),oil:Number(p.oil),daily_income:daily,assets,income_assets:incomes,rank:0}}
async function addIncome(env){const tz=await setting(env,'timezone','Asia/Tehran');const parts=new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hour12:false}).formatToParts(new Date());const get=k=>parts.find(x=>x.type===k)?.value,day=`${get('year')}-${get('month')}-${get('day')}`,hour=Number(get('hour'));if(hour!==0)return;if(await setting(env,'last_income_day','')===day)return;const ps=await env.DB.prepare('SELECT id,dollars FROM s8_players WHERE active=1').all();for(const p of ps.results||[]){const total=await incomeTotal(env,p.id);if(total>0){await env.DB.prepare('UPDATE s8_players SET dollars=dollars+?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(total,p.id).run();await env.DB.prepare('INSERT INTO s8_transactions(tx_code,player_id,type,description,amount) VALUES(?,?,?,?,?)').bind(txCode(),p.id,'income','درآمد روزانه',total).run()}}await env.DB.prepare('INSERT INTO s8_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('last_income_day',day).run()}
function bindAssetUpdate(key,delta){return `UPDATE s8_assets SET ${key}=${key}${delta>=0?'+':'-'}? WHERE player_id=?`}
export default {async scheduled(event,env,ctx){ctx.waitUntil(addIncome(env))},async fetch(req,env){const u=new URL(req.url),path=u.pathname;try{
if(path==='/api/account'&&req.method==='GET'){const code=clean(u.searchParams.get('code')).toUpperCase();if(!/^POW\d+$/.test(code))return json({message:'کد کاربری نامعتبر است.'},400);const a=await account(env,code);if(!a)return json({message:'این کد وجود ندارد'},404);if(a.blocked)return json({message:'حساب کاربری شما مسدود است.'},403);return json(a)}
if(path==='/api/catalog')return json({equipment:Object.fromEntries(Object.entries(CATALOG).map(([k,v])=>[k,v.map(x=>({name:x[0],key:x[1],price:x[2]}))])),income:INCOME.map(x=>({name:x[0],key:x[1],price:x[2],daily:x[3]}))});
if(path==='/api/season/settings'&&req.method==='GET')return json({war_enabled:(await setting(env,'war_enabled','1'))==='1',bitcoin_price:Number(await setting(env,'bitcoin_price','0')),season:8,name:'جنگ جهانی سوم'});
if(path==='/api/season/login'&&req.method==='POST'){const {code}=await req.json();const a=await auth(new Request(req.url,{headers:{'x-user-code':clean(code)}}),env);if(a.error)return a.error;return json({ok:true,code:a.user.code,country:a.player.country})}
if(path==='/api/season/me'&&req.method==='GET'){const a=await auth(req,env);if(a.error)return a.error;const p=await publicPlayer(env,a.player);const rankRows=await env.DB.prepare('SELECT id FROM s8_players WHERE active=1 ORDER BY dollars DESC,id ASC').all();p.rank=(rankRows.results||[]).findIndex(x=>x.id===a.player.id)+1;return json(p)}
if(path==='/api/season/governments'&&req.method==='GET'){const rows=await env.DB.prepare('SELECT p.* FROM s8_players p WHERE active=1 ORDER BY dollars DESC').all();const out=[];for(const p of rows.results||[])out.push(await publicPlayer(env,p));return json(out)}
if(path==='/api/season/buy'&&req.method==='POST'){const a=await auth(req,env);if(a.error)return a.error;const d=await req.json(),key=clean(d.key),qty=Math.floor(Number(d.quantity));if(!META[key]||qty<1)return json({message:'خرید نامعتبر است.'},400);const m=META[key],total=m.price*qty;if(!Number.isSafeInteger(total)||a.player.dollars<total)return json({message:'موجودی کافی نیست'},400);if(m.category==='income'){await env.DB.batch([env.DB.prepare('UPDATE s8_players SET dollars=dollars-?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(total,a.player.id),env.DB.prepare('INSERT INTO s8_income_assets(player_id,kind,qty) VALUES(?,?,?) ON CONFLICT(player_id,kind) DO UPDATE SET qty=qty+excluded.qty').bind(a.player.id,key,qty),env.DB.prepare('INSERT INTO s8_transactions(tx_code,player_id,user_code,type,description,amount,quantity,item_key) VALUES(?,?,?,?,?,?,?,?)').bind(txCode(),a.player.id,a.user.code,'buy',m.name,total,qty,key)]);return json({message:'پرداخت موفق',transaction_id:txCode()})}await env.DB.batch([env.DB.prepare('UPDATE s8_players SET dollars=dollars-?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(total,a.player.id),env.DB.prepare(`UPDATE s8_assets SET ${key}=${key}+? WHERE player_id=?`).bind(qty,a.player.id),env.DB.prepare('INSERT INTO s8_transactions(tx_code,player_id,user_code,type,description,amount,quantity,item_key) VALUES(?,?,?,?,?,?,?,?)').bind(txCode(),a.player.id,a.user.code,'buy',m.name,total,qty,key)]);return json({message:'پرداخت موفق'})}
if(path==='/api/season/transfer'&&req.method==='POST'){const a=await auth(req,env);if(a.error)return a.error;const d=await req.json(),to=clean(d.to_code).toUpperCase(),key=clean(d.key),qty=Math.floor(Number(d.quantity));const b=await env.DB.prepare('SELECT * FROM s8_players WHERE user_code=? AND active=1').bind(to).first();if(!b||b.id===a.player.id)return json({message:'گیرنده معتبر نیست.'},400);if(!['dollars','oil',...allAssetKeys].includes(key)||META[key]?.category==='income'||qty<1)return json({message:'دارایی قابل انتقال نیست.'},400);const cnt=await env.DB.prepare("SELECT COUNT(*) n FROM s8_transfers WHERE sender_player_id=? AND created_at>=date('now')").bind(a.player.id).first();if(Number(cnt?.n||0)>=3)return json({message:'سقف ۳ انتقال امروز شما پر شده است.'},400);if(key==='dollars'||key==='oil'){if(Number(a.player[key])<qty)return json({message:'موجودی کافی نیست'},400);await env.DB.batch([env.DB.prepare(`UPDATE s8_players SET ${key}=${key}-? WHERE id=?`).bind(qty,a.player.id),env.DB.prepare(`UPDATE s8_players SET ${key}=${key}+? WHERE id=?`).bind(qty,b.id)])}else{if(Number(a.player[key]||0)<qty)return json({message:'موجودی کافی نیست'},400);await env.DB.batch([env.DB.prepare(`UPDATE s8_assets SET ${key}=${key}-? WHERE player_id=?`).bind(qty,a.player.id),env.DB.prepare(`UPDATE s8_assets SET ${key}=${key}+? WHERE player_id=?`).bind(qty,b.id)])}const code=txCode();await env.DB.prepare('INSERT INTO s8_transfers(tx_code,sender_player_id,receiver_player_id,kind,asset_key,quantity) VALUES(?,?,?,?,?,?)').bind(code,a.player.id,b.id,key,key,qty).run();return json({message:'انتقال با موفقیت انجام شد',transaction_id:code})}
if(path==='/api/season/battle'&&req.method==='POST'){const a=await auth(req,env);if(a.error)return a.error;if((await setting(env,'war_enabled','1'))!=='1')return json({message:'جنگ در حال حاضر غیرفعال است.'},403);const d=await req.json(),mode=d.mode==='defense'?'defense':'war',to=clean(d.to_code).toUpperCase(),scenario=clean(d.scenario);if(!scenario)return json({message:'سناریو را وارد کنید.'},400);const defender=await env.DB.prepare('SELECT * FROM s8_players WHERE user_code=? AND active=1').bind(to).first();if(!defender||defender.id===a.player.id)return json({message:'کشور حریف معتبر نیست.'},400);const allowed=mode==='defense'?defenseKeys:warKeys,selected=d.assets||{},cleaned=[];for(const [k,v] of Object.entries(selected)){const q=Math.floor(Number(v));if(q>0){if(!allowed.includes(k))return json({message:'این تجهیز برای این نوع نبرد مجاز نیست.'},400);if(Number(a.player[k]||0)<q)return json({message:`تعداد ${META[k]?.name||k} کافی نیست.`},400);cleaned.push([k,q])}}if(!cleaned.length)return json({message:'حداقل یک تجهیز انتخاب کنید.'},400);const code=txCode();const stm=[env.DB.prepare('INSERT INTO s8_battles(code,attacker_player_id,defender_player_id,mode,scenario) VALUES(?,?,?,?,?)').bind(code,a.player.id,defender.id,mode,scenario)];for(const [k,q] of cleaned){stm.push(env.DB.prepare(`UPDATE s8_assets SET ${k}=${k}-? WHERE player_id=?`).bind(q,a.player.id));stm.push(env.DB.prepare('INSERT INTO s8_battle_assets(battle_id,asset_key,quantity) SELECT id,?,? FROM s8_battles WHERE code=?').bind(k,q,code))}await env.DB.batch(stm);return json({message:'سناریو ارسال شد'})}
if(path==='/api/season/transactions'&&req.method==='GET'){const a=await auth(req,env);if(a.error)return a.error;const r=await env.DB.prepare('SELECT tx_code,type,description,amount,quantity,created_at FROM s8_transactions WHERE player_id=? ORDER BY id DESC LIMIT 100').bind(a.player.id).all();return json(r.results||[])}
if(path==='/api/admin/login'&&req.method==='POST'){if(!env.ADMIN_PASSWORD)return json({message:'ADMIN_PASSWORD تنظیم نشده است.'},500);const d=await req.json();if(d.password!==env.ADMIN_PASSWORD)return json({message:'رمز عبور اشتباه است.'},401);return json({token:await makeToken(env)})}
if(path.startsWith('/api/admin/')){if(!(await adminOK(req,env)))return json({message:'دسترسی غیرمجاز'},401)}
if(path==='/api/admin/users'&&req.method==='GET'){const r=await env.DB.prepare('SELECT * FROM users ORDER BY id DESC').all();return json(r.results||[])}
if(path==='/api/admin/users'&&req.method==='POST'){const d=await req.json(),code=clean(d.code).toUpperCase(),name=clean(d.name),total=Math.floor(Number(d.total_games||0)),wins=Math.floor(Number(d.wins??d.victories??0));if(!/^POW\d+$/.test(code)||!name||total<0||wins<0||wins>total)return json({message:'اطلاعات نامعتبر است.'},400);const s=await userSchema(env);try{await env.DB.prepare(`INSERT INTO users(code,name,total_games,${s.victories},loyalty_date) VALUES(?,?,?,?,?)`).bind(code,name,total,wins,d.loyalty_date||new Date().toISOString()).run();return json({message:'کاربر اضافه شد'})}catch(e){return json({message:String(e).includes('UNIQUE')?'این کد قبلاً ثبت شده است.':'خطا در ثبت کاربر.'},409)}}
if(path.startsWith('/api/admin/users/')&&req.method==='PUT'){const code=decodeURIComponent(path.split('/').pop()).toUpperCase(),d=await req.json(),s=await userSchema(env);if(d.action==='block'){let until='permanent';if(d.type==='month')until=new Date(Date.now()+30*86400000).toISOString();else if(d.type==='season')until='season';await env.DB.prepare(`UPDATE users SET blocked_until=?,${s.blocked}=? WHERE code=?`).bind(until,d.type,code).run();return json({message:'کاربر مسدود شد'})}if(d.action==='unblock'){await env.DB.prepare(`UPDATE users SET blocked_until=NULL,${s.blocked}=NULL WHERE code=?`).bind(code).run();return json({message:'مسدودی برداشته شد'})}await env.DB.prepare(`UPDATE users SET name=?,total_games=?,${s.victories}=? WHERE code=?`).bind(clean(d.name),Number(d.total_games),Number(d.wins??d.victories??0),code).run();return json({message:'ویرایش شد'})}
if(path.startsWith('/api/admin/users/')&&req.method==='DELETE'){const code=decodeURIComponent(path.split('/').pop()).toUpperCase();await env.DB.prepare('DELETE FROM users WHERE code=?').bind(code).run();return json({message:'حذف شد'})}
if(path==='/api/admin/players'&&req.method==='GET'){const r=await env.DB.prepare('SELECT p.*,u.name FROM s8_players p JOIN users u ON u.code=p.user_code WHERE p.active=1 ORDER BY p.dollars DESC').all();return json(r.results||[])}
if(path==='/api/admin/players'&&req.method==='POST'){const d=await req.json(),code=clean(d.user_code).toUpperCase(),country=clean(d.country),u=await getUser(env,code);if(!u)return json({message:'کاربر وجود ندارد'},404);if(await isBlocked(u))return json({message:'کاربر مسدود است'},400);if(await env.DB.prepare('SELECT id FROM s8_players WHERE user_code=?').bind(code).first())return json({message:'این کاربر قبلاً وارد سیزن شده است.'},409);if(!country)return json({message:'کشور را وارد کنید.'},400);if(await env.DB.prepare('SELECT id FROM s8_players WHERE country=? AND active=1').bind(country).first())return json({message:'این کشور قبلاً انتخاب شده است.'},409);const r=await env.DB.prepare('INSERT INTO s8_players(user_code,country,dollars,oil) VALUES(?,?,10000,?) RETURNING id').bind(code,country,Math.max(0,Math.floor(Number(d.oil||0)))).first();await env.DB.prepare('INSERT INTO s8_assets(player_id) VALUES(?)').bind(r.id).run();return json({message:'بازیکن سیزن ۸ ثبت شد'})}
if(path.startsWith('/api/admin/players/')&&req.method==='PUT'){const id=Number(path.split('/').pop()),d=await req.json(),p=await env.DB.prepare('SELECT * FROM s8_players WHERE id=?').bind(id).first();if(!p)return json({message:'بازیکن پیدا نشد'},404);if(d.action==='country'){const c=clean(d.country);if(!c)return json({message:'کشور را وارد کنید.'},400);if(await env.DB.prepare('SELECT id FROM s8_players WHERE country=? AND id<>? AND active=1').bind(c,id).first())return json({message:'این کشور در اختیار بازیکن دیگری است.'},409);const zeros=allAssetKeys.map(k=>`${k}=0`).join(',');await env.DB.batch([env.DB.prepare('UPDATE s8_players SET country=?,dollars=10000,oil=0,income_daily=0,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(c,id),env.DB.prepare(`UPDATE s8_assets SET ${zeros} WHERE player_id=?`).bind(id),env.DB.prepare('DELETE FROM s8_income_assets WHERE player_id=?').bind(id)]);return json({message:'کشور تغییر کرد و دارایی‌ها به ۱۰٬۰۰۰ دلار بازنشانی شدند.'})}return json({message:'عملیات نامعتبر'},400)}
if(path==='/api/admin/grant'&&req.method==='POST'){const d=await req.json(),p=await env.DB.prepare('SELECT * FROM s8_players WHERE id=?').bind(Number(d.player_id)).first(),kind=clean(d.kind),q=Math.floor(Number(d.quantity));if(!p)return json({message:'بازیکن پیدا نشد'},404);if(q<1)return json({message:'مقدار نامعتبر است.'},400);if(kind==='dollars'||kind==='oil')await env.DB.prepare(`UPDATE s8_players SET ${kind}=${kind}+? WHERE id=?`).bind(q,p.id).run();else if(META[kind]&&META[kind].category!=='income')await env.DB.prepare(`UPDATE s8_assets SET ${kind}=${kind}+? WHERE player_id=?`).bind(q,p.id).run();else if(META[kind]?.category==='income')await env.DB.prepare('INSERT INTO s8_income_assets(player_id,kind,qty) VALUES(?,?,?) ON CONFLICT(player_id,kind) DO UPDATE SET qty=qty+excluded.qty').bind(p.id,kind,q).run();else return json({message:'دارایی نامعتبر است.'},400);return json({message:'اعطا شد'})}
if(path==='/api/admin/transactions'&&req.method==='GET'){const r=await env.DB.prepare('SELECT t.*,p.country FROM s8_transactions t LEFT JOIN s8_players p ON p.id=t.player_id ORDER BY t.id DESC LIMIT 500').all();return json(r.results||[])}
if(path==='/api/admin/battles'&&req.method==='GET'){const r=await env.DB.prepare(`SELECT b.*,a.country attacker_country,d.country defender_country FROM s8_battles b JOIN s8_players a ON a.id=b.attacker_player_id JOIN s8_players d ON d.id=b.defender_player_id WHERE b.status='pending' ORDER BY b.id ASC`).all();const out=[];for(const b of r.results||[]){const ar=await env.DB.prepare('SELECT asset_key,quantity FROM s8_battle_assets WHERE battle_id=?').bind(b.id).all();out.push({...b,assets:ar.results||[]})}return json(out)}
if(path.startsWith('/api/admin/battles/')&&req.method==='PUT'){const id=Number(path.split('/').pop()),d=await req.json(),b=await env.DB.prepare("SELECT * FROM s8_battles WHERE id=? AND status='pending'").bind(id).first();if(!b)return json({message:'سناریو پیدا نشد یا قبلاً بررسی شده.'},404);const rows=await env.DB.prepare('SELECT asset_key,quantity FROM s8_battle_assets WHERE battle_id=?').bind(id).all(),stm=[env.DB.prepare('UPDATE s8_battles SET status=?,reviewed_at=CURRENT_TIMESTAMP WHERE id=?').bind(d.approved?'approved':'rejected',id)];if(!d.approved)for(const r of rows.results||[])stm.push(env.DB.prepare(`UPDATE s8_assets SET ${r.asset_key}=${r.asset_key}+? WHERE player_id=?`).bind(r.quantity,b.attacker_player_id));await env.DB.batch(stm);return json({message:d.approved?'سناریو بررسی و بسته شد.':'سناریو رد شد و تجهیزات برگشت.'})}
if(path==='/api/admin/war'&&req.method==='POST'){const d=await req.json();await env.DB.prepare('INSERT INTO s8_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('war_enabled',d.enabled?'1':'0').run();return json({message:'انجام شد'})}
if(path==='/api/admin/bitcoin'&&req.method==='POST'){const price=Math.floor(Number((await req.json()).price));if(price<0)return json({message:'قیمت نامعتبر است.'},400);await env.DB.prepare('INSERT INTO s8_settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind('bitcoin_price',String(price)).run();return json({message:'قیمت بیت‌کوین ثبت شد.'})}
if(path==='/api/admin/test-state'&&req.method==='GET')return json({db:'OK',season:8,war_enabled:(await setting(env,'war_enabled','1'))==='1'});
return env.ASSETS.fetch(req)
}catch(e){return json({message:'خطای سرور',detail:String(e)},500)}}};
